/// Auth strings
const Map<String, String> authStringsEn = {
  'login_success': 'Login successful!',
  'username': 'Username',
  'password': 'Password',
  'invalid_credentials': 'Login failed, please try to log in again.',
  'email_label': "Email Address",
  'developer_mode_alert_title': 'Developer Mode Detected',
  'developer_mode_alert_message':
      'Developer mode is enabled on your device. For security, please disable developer mode to use this app.',
  'exit_app': 'Exit App',
  'connecting_google_title': 'Connecting to Google...',
  'connecting_google_subtitle': 'Please complete sign-in to continue',
  'logging_in_employee': 'Logging in...',
  'hr_system_tagline': 'Smart HR System',
  'welcome_back_title': 'Welcome Back',
  'hr_management_title': 'Smart HR Management',
  'auth_subtitle':
      'Sign in to manage your attendance, leave, and notifications in one place.',
  'feature_face_attendance_title': 'Face Attendance',
  'feature_face_attendance_desc': 'Check in and out with a quick face scan',
  'feature_leave_management_title': 'Leave Management',
  'feature_leave_management_desc': 'Apply for leave and track approval status',
  'feature_notifications_title': 'Instant Notifications',
  'feature_notifications_desc': 'Stay updated on approvals and announcements',
  'sign_in_to_continue': 'Sign in to continue',
  'signing_in': 'Signing in...',
  'continue_with_google': 'Continue with Google',
  'terms_agreement_prefix': 'By continuing, you agree to our ',
  'terms_of_service': 'Terms of Service',
  'terms_agreement_and': ' and ',
  'privacy_policy': 'Privacy Policy',
};

const Map<String, String> authStringsKm = {
  'login_success': 'ចូលគណនីជោគជ័យ!',
  'username': 'ឈ្មោះប្រើប្រាស់',
  'password': 'ពាក្យសម្ងាត់',
  'invalid_credentials': 'ការចូលគណនីបរាជ័យ សូមព្យាយាមចូលម្តងទៀត។',
  'email_label': "អាសយដ្ឋានអ៊ីមែល",
  'developer_mode_alert_title': 'បានរកឃើញ Developer Mode',
  'developer_mode_alert_message':
      'Developer mode ត្រូវបានបើកលើឧបករណ៍របស់អ្នក។ ដើម្បីសុវត្ថិភាព សូមបិទវា មុនប្រើកម្មវិធីនេះ។',
  'exit_app': 'ចាកចេញពីកម្មវិធី',
  'connecting_google_title': 'កំពុងភ្ជាប់ទៅ Google...',
  'connecting_google_subtitle': 'សូមបំពេញការចូលគណនីដើម្បីបន្ត',
  'logging_in_employee': 'កំពុងចូលគណនី...',
  'hr_system_tagline': 'ប្រព័ន្ធធនធានមនុស្សឆ្លាតវៃ',
  'welcome_back_title': 'សូមស្វាគមន៍',
  'hr_management_title': 'ការគ្រប់គ្រងធនធានមនុស្សឆ្លាតវៃ',
  'auth_subtitle':
      'ចូលគណនីដើម្បីគ្រប់គ្រងវត្តមាន ច្បាប់ឈប់សម្រាក និងការជូនដំណឹងរបស់អ្នកនៅកក្នុងកម្មវិធីតែមួយ។',
  'feature_face_attendance_title': 'ការចុះវត្តមានតាមមុខ',
  'feature_face_attendance_desc': 'ចុះវត្តមានចូល និងចេញ ដោយស្កេនមុខយ៉ាងរហ័ស',
  'feature_leave_management_title': 'ការគ្រប់គ្រងច្បាប់ឈប់សម្រាក',
  'feature_leave_management_desc':
      'ស្នើសុំច្បាប់ឈប់សម្រាក និងតាមដានស្ថានភាពអនុម័ត',
  'feature_notifications_title': 'ការជូនដំណឹងភ្លាមៗ',
  'feature_notifications_desc':
      'ទទួលបានព័ត៌មានថ្មីៗអំពីការអនុម័ត និងសេចក្តីប្រកាស',
  'sign_in_to_continue': 'ចូលគណនីដើម្បីបន្ត',
  'signing_in': 'កំពុងចូលគណនី...',
  'continue_with_google': 'បន្តជាមួយ Google',
  'terms_agreement_prefix': 'ដោយបន្ត អ្នកយល់ព្រមតាម',
  'terms_of_service': 'លក្ខខណ្ឌនៃការប្រើប្រាស់',
  'terms_agreement_and': ' និង ',
  'privacy_policy': 'គោលការណ៍ភាពឯកជន',
};
