/// Date & Time strings
const Map<String, String> dateTimeStringsEn = {
  'month_jan': 'Jan',
  'month_feb': 'Feb',
  'month_mar': 'Mar',
  'month_apr': 'Apr',
  'month_may': 'May',
  'month_jun': 'Jun',
  'month_jul': 'Jul',
  'month_aug': 'Aug',
  'month_sep': 'Sep',
  'month_oct': 'Oct',
  'month_nov': 'Nov',
  'month_dec': 'Dec',
  'monday': 'Monday',
  'tuesday': 'Tuesday',
  'wednesday': 'Wednesday',
  'thursday': 'Thursday',
  'friday': 'Friday',
  'saturday': 'Saturday',
  'sunday': 'Sunday',
  'mock_gps_label': 'Mock GPS Detected!',
  'mock_gps_warning': 'Fake GPS Detected! Please disable mock location.',
  'face_training_title': 'Register Face',
  'face_registered_success': 'Face registered successfully!',
  'scanning': 'Scanning',
  'no_face_detected': 'No face detected. Keep centered.',
  'face_not_straight': 'Keep your head straight.',
  'move_closer_full_face_required': 'Move closer. Full face is required.',
  'face_not_centered': 'Face not centered. Look straight.',
  'eyes_not_clear': 'Keep your eyes clear and open.',
  'keep_neutral_expression': 'Keep a neutral expression.',
  'bad_lighting': 'Lighting is not good. Face is unclear.',
  'face_quality_ok': 'Face quality OK. Capturing...',
  'taking_you_home': 'Taking you to Home...',
  'face_confirmed': 'Face confirmed',
  'face_validation_error': 'Face validation failed. Please try again.',
  'before_scanning_title': 'Before scanning',
  'before_scanning_desc': 'Please make sure your face is fully visible.\nRemove glasses, hat, and mask first.',
  'guide_remove_glasses': 'Remove glasses',
  'guide_no_hat_mask': 'No hat and mask',
  'start_scanning_acknowledge': 'I understand, start scanning',
};

const Map<String, String> dateTimeStringsKm = {
  'month_jan': 'មករា',
  'month_feb': 'កុម្ភៈ',
  'month_mar': 'មីនា',
  'month_apr': 'មេសា',
  'month_may': 'ឧសភា',
  'month_jun': 'មិថុនា',
  'month_jul': 'កក្កដា',
  'month_aug': 'សីហា',
  'month_sep': 'កញ្ញា',
  'month_oct': 'តុលា',
  'month_nov': 'វិច្ឆិកា',
  'month_dec': 'ធ្នូ',
  'monday': 'ថ្ងៃច័ន្ទ',
  'tuesday': 'ថ្ងៃអង្គារ',
  'wednesday': 'ថ្ងៃពុធ',
  'thursday': 'ថ្ងៃព្រហស្បតិ៍',
  'friday': 'ថ្ងៃសុក្រ',
  'saturday': 'ថ្ងៃសៅរ៍',
  'sunday': 'ថ្ងៃអាទិត្យ',
  'mock_gps_label': 'ប្រព័ន្ធ GPS ក្លែងក្លាយ!',
  'mock_gps_warning': 'រកឃើញការបន្លំ GPS! សូមបិទការកំណត់ទីតាំងក្លែងក្លាយ។',
  'face_training_title': 'ចុះឈ្មោះផ្ទៃមុខ',
  'face_registered_success': 'ការចុះឈ្មោះផ្ទៃមុខបានជោគជ័យ!',
  'scanning': 'កំពុងស្កេន',
  'no_face_detected': 'មិនបានរកឃើញមុខ។ រក្សាចំណាប់អារម្មណ៍។',
  'face_not_straight': 'សូមរក្សាក្បាលឱ្យត្រង់។',
  'move_closer_full_face_required': 'សូមចូលកាន់តែជិត។ ត្រូវការមុខពេញលេញ។',
  'face_not_centered': 'មុខមិនផ្ចិត។ មើលត្រង់ទៅ។',
  'eyes_not_clear': 'សូមបើកភ្នែកឱ្យច្បាស់។',
  'keep_neutral_expression': 'រក្សាការបង្ហាញតម្រង់ទិស។',
  'bad_lighting': 'ពន្លឺមិនល្អ។ មុខមិនច្បាស់។',
  'face_quality_ok': 'គុណភាពមុខល្អ។ កំពុងចាប់ផ្តើម...',
  'taking_you_home': 'កំពុងនាំអ្នកត្រឡប់ទៅទំព័រដើម...',
  'face_confirmed': 'បានបញ្ជាក់មុខរួចរាល់',
  'face_validation_error': 'ការផ្ទៀងផ្ទាត់មុខបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
  'before_scanning_title': 'មុនពេលស្កេន',
  'before_scanning_desc': 'សូមធានាថាមុខរបស់អ្នកបង្ហាញពេញលេញ។\nសូមដោះវ៉ែនតា មួក និងម៉ាស់ជាមុនសិន។',
  'guide_remove_glasses': 'ដោះវ៉ែនតា',
  'guide_no_hat_mask': 'គ្មានមួក និងម៉ាស់',
  'start_scanning_acknowledge': 'យល់ហើយ ចាប់ផ្តើមស្កេន',
};
