/// Face Scan strings
const Map<String, String> faceScanStringsEn = {
  'face_scan_title': 'Attendance Assessment',
  'face_pose_hint_title': 'Follow these face poses',
  'face_pose_hint_desc': 'This is a live image scan, not a video.',
  'face_pose_left': 'Look left',
  'face_pose_right': 'Look right',
  'face_pose_blink_eyes': 'Blink eyes',
  'scan_success': 'Scan Success!',
  'switch_workspace': 'Switch Workspace',
  'camera_unavailable_title': 'Camera Unavailable',
  'camera_unavailable_message': 'Unable to start the camera. It may still be in use by another part of the app. Please try again.',
  'camera_permission_required_title': 'Camera Permission Required',
  'camera_permission_denied_register': 'Camera access was denied. Please enable it in app settings to register your face.',
  'camera_permission_needed_register': 'Camera access is needed to register your face.',
  'camera_permission_denied_scan': 'Camera access was denied. Please enable it in app settings to continue.',
  'camera_permission_needed_scan': 'Camera access is needed to scan your face.',
  'open_settings_action': 'Open Settings',
  'retry_action': 'Retry',
  'face_verification_timeout': 'Face verification timed out. Please try again.',
  'face_verification_failed_retry': 'Face verification failed. Please retry.',
  'face_verification_failed_prefix': 'Face verification failed',
};

const Map<String, String> faceScanStringsKm = {
  'face_scan_title': 'ការចុះវត្តមាន',
  'face_pose_hint_title': 'ធ្វើតាមនេះ',
  'face_pose_hint_desc': 'ថតរូប មិនមែនវីដេអូ',
  'face_pose_left': 'ងាកឆ្វេង',
  'face_pose_right': 'ងាកស្តាំ',
  'face_pose_blink_eyes': 'ព្រិចភ្នែក',
  'scan_success': 'ជោគជ័យ!',
  'switch_workspace': 'ប្តូរកន្លែងធ្វើការ',
  'camera_unavailable_title': 'មិនអាចប្រើកាមេរ៉ាបានទេ',
  'camera_unavailable_message': 'មិនអាចបើកកាមេរ៉ាបានទេ។ វាអាចកំពុងប្រើដោយផ្នែកផ្សេងទៀតរបស់កម្មវិធី។ សូមព្យាយាមម្តងទៀត។',
  'camera_permission_required_title': 'ត្រូវការសិទ្ធិប្រើកាមេរ៉ា',
  'camera_permission_denied_register': 'សិទ្ធិប្រើកាមេរ៉ាត្រូវបានបដិសេធ។ សូមបើកសិទ្ធិនៅក្នុងការកំណត់កម្មវិធីដើម្បីចុះឈ្មោះមុខរបស់អ្នក។',
  'camera_permission_needed_register': 'ត្រូវការសិទ្ធិប្រើកាមេរ៉ាដើម្បីចុះឈ្មោះមុខរបស់អ្នក។',
  'camera_permission_denied_scan': 'សិទ្ធិប្រើកាមេរ៉ាត្រូវបានបដិសេធ។ សូមបើកសិទ្ធិនៅក្នុងការកំណត់កម្មវិធីដើម្បីបន្ត។',
  'camera_permission_needed_scan': 'ត្រូវការសិទ្ធិប្រើកាមេរ៉ាដើម្បីស្កេនមុខរបស់អ្នក។',
  'open_settings_action': 'បើកការកំណត់',
  'retry_action': 'ព្យាយាមម្តងទៀត',
  'face_verification_timeout': 'ការផ្ទៀងផ្ទាត់មុខអស់ពេល។ សូមព្យាយាមម្តងទៀត។',
  'face_verification_failed_retry': 'ការផ្ទៀងផ្ទាត់មុខបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
  'face_verification_failed_prefix': 'ការផ្ទៀងផ្ទាត់មុខបានបរាជ័យ',
};
