/// Leave Management & Requests strings
const Map<String, String> leaveManagementStringsEn = {
  'leave_details_title': 'Leave Details',
  'request_history': 'Leave Request History',
  'you_have_remaining_leave': 'You have',
  'this_year': 'of leave remaining for this year.',
  'remaining': 'Remaining',
  'used': 'Used',
  'request_sick_leave': 'Request Sick Leave',
  'request_annual_leave': 'Request Annual Leave',
  'status_approved': 'Approved',
  'status_rejected': 'Rejected',
  'status_pending': 'Pending',
  'days_remaining': 'Days Remaining',
  'recent_requests': 'Recent Requests',
  'remove_leave_request_title': 'Remove leave request',
  'remove_leave_request_message':
      'Are you sure you want to remove this request?',
  'remove_leave_request_not_allowed_title': 'Cannot remove approved leave',
  'remove_leave_request_not_allowed_message':
      'Approved leave requests cannot be removed.',
  'remove_button': 'Remove',
  'leave_request_removed': 'Leave request removed',
  'sort_newest_date': 'Newest Date',
  'sort_oldest_date': 'Oldest Date',
  'attachments': 'Attachments',
  'medical_report': 'Medical Report',
  'no_attachments': 'No attachments',
  'submitted_date': 'Submitted Date',
};

const Map<String, String> leaveManagementStringsKm = {
  'leave_details_title': 'ព័ត៌មានលម្អិតការឈប់សម្រាក',
  'request_history': 'ប្រវត្តិការស្នើសុំច្បាប់',
  'you_have_remaining_leave': 'អ្នកនៅសល់ច្បាប់សម្រាកចំនួន',
  'this_year': 'សម្រាប់ឆ្នាំនេះ។',
  'remaining': 'នៅសល់',
  'used': 'ប្រើអស់',
  'request_sick_leave': 'ស្នើច្បាប់ឈឺ',
  'request_annual_leave': 'ស្នើច្បាប់ប្រចាំឆ្នាំ',
  'status_approved': 'បានអនុម័ត',
  'status_rejected': 'បានបដិសេធ',
  'status_pending': 'រង់ចាំ',
  'days_remaining': 'ថ្ងៃនៅសល់',
  'recent_requests': 'សំណើថ្មីៗ',
  'remove_leave_request_title': 'លុបសំណើច្បាប់ឈប់សម្រាក',
  'remove_leave_request_message': 'តើអ្នកប្រាកដថាចង់លុបសំណើនេះមែនទេ?',
  'remove_leave_request_not_allowed_title': 'មិនអាចលុបបានទេ',
  'remove_leave_request_not_allowed_message': 'សំណើដែលបានអនុម័តមិនអាចលុបបានទេ។',
  'remove_button': 'លុប',
  'leave_request_removed': 'បានលុបសំណើច្បាប់ឈប់សម្រាក',
  'sort_newest_date': 'កាលបរិច្ឆេទថ្មីបំផុត',
  'sort_oldest_date': 'កាលបរិច្ឆេទចាស់បំផុត',
  'attachments': 'ឯកសារភ្ជាប់',
  'medical_report': 'របាយការណ៍វេជ្ជសាស្ត្រ',
  'no_attachments': 'គ្មានឯកសារភ្ជាប់ទេ',
  'submitted_date': 'ថ្ងៃដាក់សំណើ',
};
