/// Menu strings
const Map<String, String> menuStringsEn = {
  'home_menu': 'Home',
  'atd_menu': 'Attendent',
  'leave_menu': 'Leave',
  'request_menu': 'Requests',
  'task_menu': 'Tasks',
  'activity_menu': 'Activity',
  'profile_menu': 'Profile',
  'live_activity_title': 'Live Activity',
  'search_name_or_activity': 'Search name or activity...',
  'sort_newest_first': 'Newest first',
  'sort_oldest_first': 'Oldest first',
  'sort_name_az': 'Name A-Z',
  'sort_name_za': 'Name Z-A',
  'unknown_user': 'Unknown',
  'activity_title_absent': '{name} was absent',
  'activity_subtitle_absent': 'No check-in record was found for this day.',
  'activity_title_late': '{name} checked in late',
  'activity_subtitle_late': 'Check-in recorded at {time}.',
  'activity_title_on_time': '{name} checked in on time',
  'activity_subtitle_on_time': 'Attendance verified with face scan and location.',
  'activity_swipe_back_hint': 'Tip: Swipe right to go back.',
  'today': 'Today',
  'yesterday': 'Yesterday',
};

const Map<String, String> menuStringsKm = {
  'home_menu': 'ទំព័រដើម',
  'atd_menu': 'វត្តមាន',
  'leave_menu': 'ច្បាប់ឈប់សម្រាក',
  'request_menu': 'សំណើ',
  'task_menu': 'កិច្ចការ',
  'activity_menu': 'សកម្មភាព',
  'profile_menu': 'ប្រវត្តិរូប',
  'live_activity_title': 'សកម្មភាពបន្តផ្ទាល់',
  'search_name_or_activity': 'ស្វែងរកតាមឈ្មោះ ឬ សកម្មភាព...',
  'sort_newest_first': 'ថ្មីបំផុត',
  'sort_oldest_first': 'ចាស់បំផុត',
  'sort_name_az': 'ឈ្មោះ A-Z',
  'sort_name_za': 'ឈ្មោះ Z-A',
  'unknown_user': 'មិនស្គាល់',
  'activity_title_absent': '{name} អវត្តមាន',
  'activity_subtitle_absent': 'មិនមានកំណត់ត្រាចូលធ្វើការសម្រាប់ថ្ងៃនេះទេ។',
  'activity_title_late': '{name} បានចូលយឺត',
  'activity_subtitle_late': 'បានកត់ត្រាចូលម៉ោង {time}។',
  'activity_title_on_time': '{name} បានចូលទាន់ពេល',
  'activity_subtitle_on_time': 'វត្តមានត្រូវបានផ្ទៀងផ្ទាត់ដោយស្កេនមុខ និងទីតាំង។',
  'activity_swipe_back_hint': 'ចំណាំ៖ អូសទៅស្តាំ ដើម្បីត្រឡប់ក្រោយ។',
  'today': 'ថ្ងៃនេះ',
  'yesterday': 'ម្សិលមិញ',
};
