/// Menu strings
const Map<String, String> menuStringsEn = {
  'home_menu': 'Home',
  'atd_menu': 'Attendent',
  'leave_menu': 'Leave',
  'request_menu': 'Requests',
  'task_menu': 'Tasks',
  'activity_menu': 'Activity',
  'profile_menu': 'Profile',
  'live_activity_title': 'Live Activity',
  'search_name_or_activity': 'Search name or activity...',
  'sort_newest_first': 'Newest first',
  'sort_oldest_first': 'Oldest first',
  'sort_name_az': 'Name A-Z',
  'sort_name_za': 'Name Z-A',
  'unknown_user': 'Unknown',
  'activity_title_absent': '{name} was absent',
  'activity_subtitle_absent': 'No check-in record was found for this day.',
  'activity_title_late': '{name} checked in late',
  'activity_subtitle_late': 'Check-in recorded at {time}.',
  'activity_title_on_time': '{name} checked in on time',
  'activity_subtitle_on_time': 'Attendance verified with face scan and location.',
  'activity_swipe_back_hint': 'Tip: Swipe right to go back.',
  'today': 'Today',
  'yesterday': 'Yesterday',
  'task_status_update_failed': 'Failed to update status',
  'request_submit_failed': 'Failed to submit request',
  'request_status_pending': 'Pending',
  'request_status_seen': 'Seen',
  'request_status_in_progress': 'In Progress',
  'request_status_completed': 'Completed',
  'no_tasks_yet': 'No tasks yet',
  'update_status_title': 'Update status',
  'update_status_button': 'Update Status',
  'updating_status': 'Updating...',
  'task_details_title': 'Task Details',
  'priority_label': 'Priority',
  'deadline_label': 'Deadline',
  'description_label': 'Description',
  'no_description_provided': 'No description provided.',
  'assigned_to_label': 'Assigned to',
  'no_requests_yet': 'No requests yet',
  'new_request_title': 'New Request',
  'title_label': 'Title',
  'title_required': 'Title is required',
  'description_required': 'Description is required',
  'attachments_optional_label': 'Attachments (optional)',
  'submit_request_button': 'Submit Request',
  'close_image_label': 'Close image',
  'request_details_title': 'Request Details',
  'submitted_on': 'Submitted {date}',
  'response_label': 'Response',
  'delete_request_title': 'Delete Request?',
  'delete_request_confirm_desc':
      'This will permanently remove this pending request. This action cannot be undone.',
  'delete_button': 'Delete',
  'request_delete_failed': 'Failed to delete request',
};

const Map<String, String> menuStringsKm = {
  'home_menu': 'ទំព័រដើម',
  'atd_menu': 'វត្តមាន',
  'leave_menu': 'ច្បាប់ឈប់សម្រាក',
  'request_menu': 'សំណើ',
  'task_menu': 'កិច្ចការ',
  'activity_menu': 'សកម្មភាព',
  'profile_menu': 'ប្រវត្តិរូប',
  'live_activity_title': 'សកម្មភាពបន្តផ្ទាល់',
  'search_name_or_activity': 'ស្វែងរកតាមឈ្មោះ ឬ សកម្មភាព...',
  'sort_newest_first': 'ថ្មីបំផុត',
  'sort_oldest_first': 'ចាស់បំផុត',
  'sort_name_az': 'ឈ្មោះ A-Z',
  'sort_name_za': 'ឈ្មោះ Z-A',
  'unknown_user': 'មិនស្គាល់',
  'activity_title_absent': '{name} អវត្តមាន',
  'activity_subtitle_absent': 'មិនមានកំណត់ត្រាចូលធ្វើការសម្រាប់ថ្ងៃនេះទេ។',
  'activity_title_late': '{name} បានចូលយឺត',
  'activity_subtitle_late': 'បានកត់ត្រាចូលម៉ោង {time}។',
  'activity_title_on_time': '{name} បានចូលទាន់ពេល',
  'activity_subtitle_on_time': 'វត្តមានត្រូវបានផ្ទៀងផ្ទាត់ដោយស្កេនមុខ និងទីតាំង។',
  'activity_swipe_back_hint': 'ចំណាំ៖ អូសទៅស្តាំ ដើម្បីត្រឡប់ក្រោយ។',
  'today': 'ថ្ងៃនេះ',
  'yesterday': 'ម្សិលមិញ',
  'task_status_update_failed': 'មិនអាចធ្វើបច្ចុប្បន្នភាពស្ថានភាពបានទេ',
  'request_submit_failed': 'មិនអាចដាក់ស្នើសំណើបានទេ',
  'request_status_pending': 'រង់ចាំ',
  'request_status_seen': 'បានឃើញ',
  'request_status_in_progress': 'កំពុងដំណើរការ',
  'request_status_completed': 'បានបញ្ចប់',
  'no_tasks_yet': 'មិនទាន់មានកិច្ចការទេ',
  'update_status_title': 'ធ្វើបច្ចុប្បន្នភាពស្ថានភាព',
  'update_status_button': 'ធ្វើបច្ចុប្បន្នភាពស្ថានភាព',
  'updating_status': 'កំពុងធ្វើបច្ចុប្បន្នភាព...',
  'task_details_title': 'ព័ត៌មានលម្អិតកិច្ចការ',
  'priority_label': 'អាទិភាព',
  'deadline_label': 'ពេលកំណត់',
  'description_label': 'ការពិពណ៌នា',
  'no_description_provided': 'មិនមានការពិពណ៌នាទេ។',
  'assigned_to_label': 'ប្រគល់ឱ្យ',
  'no_requests_yet': 'មិនទាន់មានសំណើទេ',
  'new_request_title': 'សំណើថ្មី',
  'title_label': 'ចំណងជើង',
  'title_required': 'ត្រូវការចំណងជើង',
  'description_required': 'ត្រូវការការពិពណ៌នា',
  'attachments_optional_label': 'ឯកសារភ្ជាប់ (មិនចាំបាច់)',
  'submit_request_button': 'ដាក់ស្នើសំណើ',
  'close_image_label': 'បិទរូបភាព',
  'request_details_title': 'ព័ត៌មានលម្អិតសំណើ',
  'submitted_on': 'បានដាក់ស្នើ {date}',
  'response_label': 'ការឆ្លើយតប',
  'delete_request_title': 'លុបសំណើ?',
  'delete_request_confirm_desc':
      'សកម្មភាពនេះនឹងលុបសំណើដែលកំពុងរង់ចាំនេះជាអចិន្ត្រៃយ៍ ហើយមិនអាចត្រឡប់វិញបានទេ។',
  'delete_button': 'លុប',
  'request_delete_failed': 'មិនអាចលុបសំណើបានទេ',
};
