/// Profile strings
const Map<String, String> profileStringsEn = {
  'account_title': 'Account',
  'choose_photo': 'Choose Photo',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'phone_label': 'Phone Number',
  'not_connected': 'Not Connected',
  'connected': 'Connected',
  'connect_now': 'Connect Now',
  'logout_action': 'Logout',
  'confirm_logout_title': 'Logout Account',
  'confirm_logout_msg': 'Are you sure you want to logout?',
  'cancel_button': 'Cancel',
  'logout_button': 'Logout',
  'unable_to_resolve_user_id': 'Unable to resolve user id.',
  'unable_to_resolve_workspace': 'Unable to resolve workspace.',
  'profile_image_updated_successfully': 'Profile image updated successfully.',
  'profile_image_upload_failed': 'Failed to upload profile image',
  'face_sample_upload_failed': 'Failed to upload face sample',
  'attendance_scan_save_failed': 'Failed to save attendance record',
  'attendance_scan_submitting': 'Syncing attendance with the server',
  'workspace_label': 'Workspace',
  'edit_profile_action': 'Edit Profile',
  'edit_profile_title': 'Edit Profile',
  'name_label': 'Name',
  'gender_label': 'Gender',
  'gender_male': 'Male',
  'gender_female': 'Female',
  'gender_other': 'Other',
  'gender_unknown': 'Unspecified',
  'save_button': 'Save',
  'name_required': 'Name cannot be empty',
  'profile_updated_successfully': 'Profile updated successfully.',
  'profile_update_failed': 'Failed to update profile',
  'logout_failed': 'Logout failed, please try again',
  'update_face_action': 'Update Face',
  'update_face_explain_title': 'Update Your Face',
  'update_face_step_reauth': 'Re-authenticate with Google to confirm it\'s really you.',
  'update_face_step_verify': 'Verify your current face against the one on file.',
  'update_face_step_capture': 'Capture a new face to replace the old one.',
  'update_face_continue': 'Continue',
  'update_face_cooldown_title': 'Please Wait',
  'update_face_cooldown_msg': 'You can update your face again starting',
  'update_face_reauth_failed': 'Re-authentication failed. Please try again.',
  'update_face_reauth_cancelled': 'Re-authentication was cancelled.',
  'update_face_reauth_mismatch': 'That Google account doesn\'t match your signed-in account.',
  'identity_verified_title': 'Identity Verified',
  'identity_verified_desc': 'Your identity has been confirmed. You can now capture your new face.',
  'verify_identity_title': 'Verify Identity',
  'crop_profile_photo': 'Crop Profile Photo',
};

const Map<String, String> profileStringsKm = {
  'account_title': 'គណនី',
  'choose_photo': 'ជ្រើសរើសរូបថត',
  'gallery': 'បណ្ណាល័យ',
  'camera': 'ម៉ាស៊ីនថត',
  'phone_label': 'លេខទូរស័ព្ទ',
  'not_connected': 'មិនទាន់ភ្ជាប់',
  'connected': 'បានភ្ជាប់',
  'connect_now': 'ភ្ជាប់ឥឡូវ',
  'logout_action': 'ចាកចេញពីគណនី',
  'confirm_logout_title': 'ចាកចេញពីគណនី',
  'confirm_logout_msg': 'តើអ្នកប្រាកដជាចង់ចាកចេញមែនទេ?',
  'cancel_button': 'បោះបង់',
  'logout_button': 'ចាកចេញ',
  'unable_to_resolve_user_id': 'មិនអាចកំណត់អត្តសញ្ញាណអ្នកប្រើបានទេ។',
  'unable_to_resolve_workspace': 'មិនអាចកំណត់អត្តសញ្ញាណកន្លែងធ្វើការបានទេ។',
  'profile_image_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពរូបភាពប្រវត្តិរូបដោយជោគជ័យ។',
  'profile_image_upload_failed': 'មិនអាចអាប់ឡូដរូបភាពប្រវត្តិរូបបានទេ',
  'face_sample_upload_failed': 'មិនអាចអាប់ឡូដរូបថតមុខបានទេ',
  'attendance_scan_save_failed': 'មិនអាចរក្សាទុកកំណត់ត្រាវត្តមានបានទេ',
  'attendance_scan_submitting': 'កំពុងធ្វើសមកាលកម្មវត្តមានជាមួយម៉ាស៊ីនមេ',
  'workspace_label': 'កន្លែងធ្វើការ',
  'edit_profile_action': 'កែប្រែប្រវត្តិរូប',
  'edit_profile_title': 'កែប្រែប្រវត្តិរូប',
  'name_label': 'ឈ្មោះ',
  'gender_label': 'ភេទ',
  'gender_male': 'ប្រុស',
  'gender_female': 'ស្រី',
  'gender_other': 'ផ្សេងទៀត',
  'gender_unknown': 'មិនបញ្ជាក់',
  'save_button': 'រក្សាទុក',
  'name_required': 'សូមបញ្ចូលឈ្មោះ',
  'profile_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបដោយជោគជ័យ។',
  'profile_update_failed': 'មិនអាចធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបបានទេ',
  'logout_failed': 'ចាកចេញមិនបានសម្រេចទេ សូមព្យាយាមម្តងទៀត',
  'update_face_action': 'ធ្វើបច្ចុប្បន្នភាពមុខ',
  'update_face_explain_title': 'ធ្វើបច្ចុប្បន្នភាពមុខរបស់អ្នក',
  'update_face_step_reauth': 'ផ្ទៀងផ្ទាត់ម្តងទៀតជាមួយ Google ដើម្បីបញ្ជាក់ថាជាអ្នកពិតប្រាកដ។',
  'update_face_step_verify': 'ផ្ទៀងផ្ទាត់មុខបច្ចុប្បន្នរបស់អ្នកជាមួយទិន្នន័យដែលបានកត់ត្រា។',
  'update_face_step_capture': 'ថតមុខថ្មីដើម្បីជំនួសមុខចាស់។',
  'update_face_continue': 'បន្ត',
  'update_face_cooldown_title': 'សូមរង់ចាំ',
  'update_face_cooldown_msg': 'អ្នកអាចធ្វើបច្ចុប្បន្នភាពមុខម្តងទៀតបានចាប់ពី',
  'update_face_reauth_failed': 'ការផ្ទៀងផ្ទាត់ម្តងទៀតបានបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
  'update_face_reauth_cancelled': 'ការផ្ទៀងផ្ទាត់ម្តងទៀតត្រូវបានបោះបង់។',
  'update_face_reauth_mismatch': 'គណនី Google នោះមិនត្រូវគ្នាជាមួយគណនីដែលអ្នកបានចូលនោះទេ។',
  'identity_verified_title': 'អត្តសញ្ញាណបានផ្ទៀងផ្ទាត់',
  'identity_verified_desc': 'អត្តសញ្ញាណរបស់អ្នកត្រូវបានបញ្ជាក់។ ឥឡូវនេះអ្នកអាចថតមុខថ្មីរបស់អ្នកបាន។',
  'verify_identity_title': 'ផ្ទៀងផ្ទាត់អត្តសញ្ញាណ',
  'crop_profile_photo': 'កាត់តម្រឹមរូបភាពប្រវត្តិរូប',
};
