/// Profile strings
const Map<String, String> profileStringsEn = {
  'account_title': 'Account',
  'choose_photo': 'Choose Photo',
  'gallery': 'Gallery',
  'camera': 'Camera',
  'phone_label': 'Phone Number',
  'not_connected': 'Not Connected',
  'connected': 'Connected',
  'connect_now': 'Connect Now',
  'change_password_action': 'Change Password',
  'logout_action': 'Logout',
  'confirm_logout_title': 'Logout Account',
  'confirm_logout_msg': 'Are you sure you want to logout?',
  'cancel_button': 'Cancel',
  'logout_button': 'Logout',
  'unable_to_resolve_user_id': 'Unable to resolve user id.',
  'profile_image_updated_successfully': 'Profile image updated successfully.',
  'profile_image_upload_failed': 'Failed to upload profile image',
  'face_sample_upload_failed': 'Failed to upload face sample',
  'attendance_scan_save_failed': 'Failed to save attendance record',
  'attendance_scan_submitting': 'Syncing attendance with the server',
  'workspace_label': 'Workspace',
  'edit_profile_action': 'Edit Profile',
  'edit_profile_title': 'Edit Profile',
  'name_label': 'Name',
  'gender_label': 'Gender',
  'gender_male': 'Male',
  'gender_female': 'Female',
  'gender_other': 'Other',
  'gender_unknown': 'Unspecified',
  'save_button': 'Save',
  'name_required': 'Name cannot be empty',
  'profile_updated_successfully': 'Profile updated successfully.',
  'profile_update_failed': 'Failed to update profile',
  'logout_failed': 'Logout failed, please try again',
};

const Map<String, String> profileStringsKm = {
  'account_title': 'គណនី',
  'choose_photo': 'ជ្រើសរើសរូបថត',
  'gallery': 'បណ្ណាល័យ',
  'camera': 'ម៉ាស៊ីនថត',
  'phone_label': 'លេខទូរស័ព្ទ',
  'not_connected': 'មិនទាន់ភ្ជាប់',
  'connected': 'បានភ្ជាប់',
  'connect_now': 'ភ្ជាប់ឥឡូវ',
  'change_password_action': 'ប្តូរលេខសម្ងាត់',
  'logout_action': 'ចាកចេញពីគណនី',
  'confirm_logout_title': 'ចាកចេញពីគណនី',
  'confirm_logout_msg': 'តើអ្នកប្រាកដជាចង់ចាកចេញមែនទេ?',
  'cancel_button': 'បោះបង់',
  'logout_button': 'ចាកចេញ',
  'unable_to_resolve_user_id': 'មិនអាចកំណត់អត្តសញ្ញាណអ្នកប្រើបានទេ។',
  'profile_image_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពរូបភាពប្រវត្តិរូបដោយជោគជ័យ។',
  'profile_image_upload_failed': 'មិនអាចអាប់ឡូដរូបភាពប្រវត្តិរូបបានទេ',
  'face_sample_upload_failed': 'មិនអាចអាប់ឡូដរូបថតមុខបានទេ',
  'attendance_scan_save_failed': 'មិនអាចរក្សាទុកកំណត់ត្រាវត្តមានបានទេ',
  'attendance_scan_submitting': 'កំពុងធ្វើសមកាលកម្មវត្តមានជាមួយម៉ាស៊ីនមេ',
  'workspace_label': 'កន្លែងធ្វើការ',
  'edit_profile_action': 'កែប្រែប្រវត្តិរូប',
  'edit_profile_title': 'កែប្រែប្រវត្តិរូប',
  'name_label': 'ឈ្មោះ',
  'gender_label': 'ភេទ',
  'gender_male': 'ប្រុស',
  'gender_female': 'ស្រី',
  'gender_other': 'ផ្សេងទៀត',
  'gender_unknown': 'មិនបញ្ជាក់',
  'save_button': 'រក្សាទុក',
  'name_required': 'សូមបញ្ចូលឈ្មោះ',
  'profile_updated_successfully': 'បានធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបដោយជោគជ័យ។',
  'profile_update_failed': 'មិនអាចធ្វើបច្ចុប្បន្នភាពប្រវត្តិរូបបានទេ',
  'logout_failed': 'ចាកចេញមិនបានសម្រេចទេ សូមព្យាយាមម្តងទៀត',
};
