/// Sick Leave Request Screen strings
const Map<String, String> sickLeaveRequestStringsEn = {
  'request_sick_leave_title': 'Sick Leave Request',
  'leave_type': 'Leave Type',
  'request_details': 'Request Details',
  'reason_for_sickness': 'Reason for Sickness',
  'sickness_reason_hint': 'Describe symptoms...',
  'leave_date': 'Leave Date',
  'medical_documents': 'Medical Documents',
  'submit_official_request': 'Submit Official Request',
  'validation_reason_required_sickness': 'Please enter reason for sickness',
  'validation_reason_required_request': 'Please enter reason for request',
  'validation_reason_min_chars': 'Reason must be at least 5 characters',
  'validation_upload_medical_document': 'Please upload a medical document',
  'validation_select_start_end_date': 'Please select start and end date',
  'annual_request_submitted': 'Annual leave request submitted successfully',
  'sick_request_submitted': 'Sick leave request submitted successfully',
  'leave_request_submit_failed': 'Failed to submit leave request. Please try again.',
  'annual_leave_no_remaining_days': 'You have no annual leave days remaining.',
  'sick_leave_no_remaining_days': 'You have no sick leave days remaining.',
  'annual_leave_duration_exceeds_remaining': 'Requested {requestedDays} day(s), but only {remainingDays} day(s) remaining.',
  'annual_leave_end_date_must_be_after_start': 'End date must be at least one day after start date.',
  'leave_date_already_requested': 'This date has already been requested. Please choose another date.',
  'leave_range_already_requested': 'Some dates in this range have already been requested. Please choose another range.',
  'leave_no_available_dates': 'No available dates to request in this period.',
  'annual_leave_duration_toggle_title': 'Request duration leave',
  'annual_leave_duration_toggle_subtitle_single': 'One-day mode is active. Select one date only.',
  'annual_leave_duration_toggle_subtitle_duration': 'Duration mode is active. Select start and end dates.',
  'annual_leave_mode_single_day': 'One day',
  'annual_leave_mode_duration': 'Duration',
  'annual_leave_date_mode_hint': 'Tip: Enable duration mode if you need more than one day.',
  'total_leave_label': 'Total',
  'attachment_type_not_allowed': 'Only PNG and JPG images are allowed.',
  'sick_leave_active_limit_reached': 'You already have {count} active sick leave request(s). Please wait for approval or remove an existing request.',
};

const Map<String, String> sickLeaveRequestStringsKm = {
  'request_sick_leave_title': 'ពាក្យសុំច្បាប់ឈឺ',
  'leave_type': 'ប្រភេទច្បាប់',
  'request_details': 'ព័ត៌មានលម្អិតនៃសំណើ',
  'reason_for_sickness': 'មូលហេតុនៃជំងឺ',
  'sickness_reason_hint': 'បញ្ជាក់ពីអាការៈជំងឺ...',
  'leave_date': 'កាលបរិច្ឆេទឈប់សម្រាក',
  'medical_documents': 'ឯកសារវេជ្ជសាស្ត្រ',
  'submit_official_request': 'បញ្ជូនសំណើផ្លូវការ',
  'validation_reason_required_sickness': 'សូមបញ្ចូលមូលហេតុនៃជំងឺ',
  'validation_reason_required_request': 'សូមបញ្ចូលមូលហេតុនៃការស្នើសុំ',
  'validation_reason_min_chars': 'មូលហេតុត្រូវមានយ៉ាងតិច ៥ តួអក្សរ',
  'validation_upload_medical_document': 'សូមភ្ជាប់ឯកសារវេជ្ជសាស្ត្រ',
  'validation_select_start_end_date': 'សូមជ្រើសរើសថ្ងៃចាប់ផ្តើម និងថ្ងៃបញ្ចប់',
  'annual_request_submitted': 'សំណើច្បាប់ប្រចាំឆ្នាំត្រូវបានផ្ញើដោយជោគជ័យ',
  'sick_request_submitted': 'សំណើច្បាប់ឈឺត្រូវបានផ្ញើដោយជោគជ័យ',
  'leave_request_submit_failed': 'ការផ្ញើសំណើឈប់សម្រាកបរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
  'annual_leave_no_remaining_days': 'អ្នកមិនមានថ្ងៃឈប់សម្រាកប្រចាំឆ្នាំនៅសល់ទេ។',
  'sick_leave_no_remaining_days': 'អ្នកមិនមានថ្ងៃឈប់សម្រាកឈឺនៅសល់ទេ។',
  'annual_leave_duration_exceeds_remaining': 'បានស្នើសុំ {requestedDays} ថ្ងៃ ប៉ុន្តែមានសល់ត្រឹម {remainingDays} ថ្ងៃប៉ុណ្ណោះ។',
  'annual_leave_end_date_must_be_after_start': 'ថ្ងៃបញ្ចប់ត្រូវតែយ៉ាងហោចណាស់មួយថ្ងៃបន្ទាប់ពីថ្ងៃចាប់ផ្តើម។',
  'leave_date_already_requested': 'កាលបរិច្ឆេទនេះត្រូវបានស្នើសុំរួចហើយ។ សូមជ្រើសរើសកាលបរិច្ឆេទផ្សេង។',
  'leave_range_already_requested': 'មានកាលបរិច្ឆេទខ្លះក្នុងជួរនេះត្រូវបានស្នើសុំរួចហើយ។ សូមជ្រើសរើសជួរថ្មី។',
  'leave_no_available_dates': 'មិនមានកាលបរិច្ឆេទទំនេរសម្រាប់ស្នើសុំក្នុងរយៈពេលនេះទេ។',
  'annual_leave_duration_toggle_title': 'ស្នើសុំឈប់សម្រាកជាច្រើនថ្ងៃ',
  'annual_leave_duration_toggle_subtitle_single': 'ម៉ូដមួយថ្ងៃកំពុងដំណើរការ។ សូមជ្រើសរើសកាលបរិច្ឆេទតែមួយ។',
  'annual_leave_duration_toggle_subtitle_duration': 'ម៉ូដរយៈពេលកំពុងដំណើរការ។ សូមជ្រើសរើសថ្ងៃចាប់ផ្តើម និងបញ្ចប់។',
  'annual_leave_mode_single_day': 'មួយថ្ងៃ',
  'annual_leave_mode_duration': 'រយៈពេល',
  'annual_leave_date_mode_hint': 'គន្លឹះ៖ បើត្រូវការឈប់លើសមួយថ្ងៃ សូមបើកម៉ូដរយៈពេល។',
  'total_leave_label': 'សរុប',
  'attachment_type_not_allowed': 'អនុញ្ញាតតែរូបភាព PNG និង JPG ប៉ុណ្ណោះ។',
  'sick_leave_active_limit_reached': 'អ្នកមានសំណើច្បាប់ឈឺសកម្មចំនួន {count} រួចហើយ។ សូមរង់ចាំការអនុម័ត ឬលុបសំណើដែលមានស្រាប់។',
};
